# Generated by Django 4.2.3 on 2023-07-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('planned_date', models.DateField()),
                ('theme', models.CharField(max_length=100)),
                ('qualification', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('En Espera', 'En Espera')], default='Pendiente', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('Gestor', 'Gestor'), ('Tutor', 'Tutor'), ('Estudiante', 'Estudiante')], default='Estudiante', max_length=30)),
                ('estado', models.BooleanField()),
                ('tutorings', models.ManyToManyField(to='Academica.tutoring')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('parallel', models.CharField(max_length=10)),
                ('subjects', models.ManyToManyField(to='Academica.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cycles', models.ManyToManyField(to='Academica.cycle')),
            ],
        ),
    ]
