# Generated by Django 4.2.2 on 2023-08-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('parallel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tutoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('planned_date', models.DateField()),
                ('theme', models.CharField(max_length=100)),
                ('qualification', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('En Espera', 'En Espera')], default='Pendiente', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('Gestor', 'Gestor'), ('Tutor', 'Tutor'), ('Estudiante', 'Estudiante')], default='Estudiante', max_length=30)),
                ('state', models.BooleanField(default=False)),
                ('careers', models.ManyToManyField(blank=True, to='Academica.career')),
                ('cycles', models.ManyToManyField(blank=True, to='Academica.cycle')),
                ('subjects', models.ManyToManyField(blank=True, to='Academica.subject')),
                ('tutorings', models.ManyToManyField(blank=True, to='Academica.tutoring')),
            ],
        ),
        migrations.AddField(
            model_name='cycle',
            name='subjects',
            field=models.ManyToManyField(to='Academica.subject'),
        ),
        migrations.AddField(
            model_name='career',
            name='cycles',
            field=models.ManyToManyField(to='Academica.cycle'),
        ),
    ]
