# Generated by Django 4.2.3 on 2023-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0003_rename_estado_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tutorings',
            field=models.ManyToManyField(blank=True, to='Academica.tutoring'),
        ),
    ]
